stages:
  - test
  - publish

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci/scala

test:
  stage: test
  tags:
    - wopr
  script:
    - sbt +clean coverage +test coverageReport
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-snapshot:
  stage: publish
  tags:
    - wopr
  script:
    - sbt +publish
  only:
    - develop
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release-master:
  stage: publish
  tags:
    - wopr
  script:
    - /scripts/release.sh -b -r develop
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
